/**
 * Hybrid YouTube Transcript Extraction Strategy
 *
 * Combines fast InnerTube API method with DOM scraping fallback.
 * Provides best-of-both-worlds approach:
 * - Fast method: ~100-300ms (95%+ success rate)
 * - DOM fallback: ~5-10s (covers edge cases)
 *
 * This is the recommended method for production use.
 */

import { extractVideoId, extractYouTubeContext } from './youtubeTranscript';
import { fetchFirstAvailableTranscript, extractChaptersFromInnerTubeDescription } from './youtubeTranscriptFast';
import type { VideoContext } from '~types/transcript';

/**
 * Get video metadata from DOM
 *
 * Extracts title, URL, channel from current YouTube page
 * Used by fast method (which doesn't parse DOM)
 *
 * @returns Metadata object
 */
function getVideoMetadata(): {
  title: string;
  url: string;
  channel: string;
} {
  // Try multiple selectors for title (YouTube changes these)
  const titleElement =
    document.querySelector("h1.ytd-video-primary-info-renderer") ||
    document.querySelector("h1.title") ||
    document.querySelector("ytd-watch-metadata h1") ||
    document.querySelector("h1 yt-formatted-string");

  const title = titleElement?.textContent?.trim() || "Unknown Video";

  // URL is easy
  const url = window.location.href;

  // Try multiple selectors for channel
  const channelElement =
    document.querySelector("ytd-channel-name a") ||
    document.querySelector("#channel-name a") ||
    document.querySelector("ytd-video-owner-renderer .ytd-channel-name a");

  const channel = channelElement?.textContent?.trim() || "Unknown Channel";

  return { title, url, channel };
}

/**
 * Hybrid transcript extraction strategy
 *
 * Attempts fast InnerTube API method first
 * Falls back to DOM scraping if API fails
 *
 * Performance:
 * - Fast method: ~100-300ms (95%+ success rate)
 * - DOM fallback: ~5-10s (edge cases)
 *
 * @returns VideoContext with transcript + metadata
 * @throws Error if both methods fail
 *
 * @example
 * const context = await extractYouTubeContextHybrid();
 * console.log(context.transcript);
 */
export async function extractYouTubeContextHybrid(): Promise<VideoContext> {
  const overallStart = Date.now();

  // Extract video ID from URL
  const videoId = extractVideoId(window.location.href);

  if (videoId === "unknown") {
    throw new Error("Could not extract video ID from URL");
  }

  // ATTEMPT 1: Fast InnerTube API method
  try {
    console.log('[Transcript] 🚀 Attempting fast InnerTube API extraction...');
    const fastStart = Date.now();

    // Fetch transcript via API (first available subtitle)
    const result = await fetchFirstAvailableTranscript(videoId);

    const fastDuration = Date.now() - fastStart;
    console.log(
      `[Transcript] ✅ Fast method succeeded in ${fastDuration}ms: ` +
      `${result.languageName} (${result.isAutoGenerated ? 'auto' : 'manual'})`
    );

    // Get metadata from DOM (fast - no waiting)
    const { title, url, channel } = getVideoMetadata();

    // Extract chapters from InnerTube API description
    console.log('[Transcript] 📑 Extracting chapters from InnerTube description...');
    const chapters = await extractChaptersFromInnerTubeDescription(videoId);
    console.log(`[Transcript] 📑 Chapter extraction complete. Found ${chapters?.length ?? 0} chapters`);
    if (chapters && chapters.length > 0) {
      console.log('[Transcript] 📑 Chapter titles:', chapters.map(c => c.title));
    }

    const totalDuration = Date.now() - overallStart;
    console.log(`[Transcript] 🎉 Hybrid extraction completed in ${totalDuration}ms via FAST method`);

    return {
      videoId,
      transcript: result.transcript,
      title,
      url,
      channel,
      timestamp: Date.now(),
      chapters
    };

  } catch (fastError) {
    // Fast method failed - log and fall back
    const fastDuration = Date.now() - overallStart;
    console.warn(
      `[Transcript] ⚠️ Fast method failed after ${fastDuration}ms:`,
      (fastError as Error).message
    );
    console.log('[Transcript] 🔄 Falling back to DOM scraping method...');

    // ATTEMPT 2: DOM scraping fallback
    try {
      const fallbackStart = Date.now();

      // Use existing DOM scraping method
      const videoContext = await extractYouTubeContext();

      // Extract chapters from InnerTube API description
      console.log('[Transcript] 📑 Extracting chapters from InnerTube description (DOM fallback path)...');
      const chapters = await extractChaptersFromInnerTubeDescription(videoId);
      console.log(`[Transcript] 📑 Chapter extraction complete. Found ${chapters?.length ?? 0} chapters`);
      if (chapters && chapters.length > 0) {
        console.log('[Transcript] 📑 Chapter titles:', chapters.map(c => c.title));
      }

      const fallbackDuration = Date.now() - fallbackStart;
      const totalDuration = Date.now() - overallStart;

      console.log(
        `[Transcript] ✅ DOM fallback succeeded in ${fallbackDuration}ms ` +
        `(total: ${totalDuration}ms)`
      );

      return {
        ...videoContext,
        chapters
      };

    } catch (domError) {
      // Both methods failed - give up
      const totalDuration = Date.now() - overallStart;

      console.error(`[Transcript] ❌ Both methods failed after ${totalDuration}ms`);
      console.error('Fast method error:', fastError);
      console.error('DOM method error:', domError);

      // Instead of throwing, return a context object with an error message
      const { title, url, channel } = getVideoMetadata();

      // Try to extract chapters from InnerTube description (might still work even if transcript failed)
      console.log('[Transcript] 📑 Attempting chapter extraction despite transcript failure...');
      const chapters = await extractChaptersFromInnerTubeDescription(videoId);
      console.log(`[Transcript] 📑 Chapter extraction complete. Found ${chapters?.length ?? 0} chapters`);
      if (chapters && chapters.length > 0) {
        console.log('[Transcript] 📑 Chapter titles:', chapters.map(c => c.title));
      }

      return {
        videoId,
        title,
        url,
        channel,
        timestamp: Date.now(),
        chapters,
        error: `Failed to extract transcript using all available methods. InnerTube API: ${(fastError as Error).message}. DOM scraping: ${(domError as Error).message}`
      };
    }
  }
}

// Re-export API functions for direct use
export {
  listAvailableSubtitles,
  fetchTranscriptByLanguage,
  fetchFirstAvailableTranscript
} from './youtubeTranscriptFast';

// Re-export types
export type { SubtitleTrack } from './youtubeTranscriptFast';
